name: Keep Services Alive

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run keep-alive script
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: node keep-alive.js